"""Crear modelo Promocion y vista para modal

Revision ID: 049158838a67
Revises: 6cbc0d694aa0
Create Date: 2025-07-31 10:00:32.864353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049158838a67'
down_revision = '6cbc0d694aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('link_producto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocion')
    # ### end Alembic commands ###
